job1:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  script: 
  - set +e && source /cvmfs/cms.cern.ch/cmsset_default.sh; set -e
  - scramv1 project CMSSW CMSSW_9_4_0
  - echo "hi"