job1:
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  before_script: 
  - cd ..
  - tar czf repo.tar.gz ltau_analyzers
  - set +e && source /cvmfs/cms.cern.ch/cmsset_default.sh; set -e
  - export SCRAM_ARCH=slc6_amd64_gcc630
  - scramv1 project CMSSW CMSSW_9_4_0
  - cd CMSSW_9_4_0/src
  - mv ../../repo.tar.gz .
  - tar xzf repo.tar.gz
  - eval `scramv1 runtime -sh`
  - git clone -b tauTriggers2017_reMiniaod_test https://github.com/truggles/TauTriggerSFs2017.git TauTriggerSFs2017
  - git clone https://github.com/CMS-HTT/Jet2TauFakes.git HTTutilities/Jet2TauFakes
  - cd HTTutilities/Jet2TauFakes
  - git checkout v0.2.2
  - scram b
  - mkdir data
  - git clone -b 2017 https://gitlab.cern.ch/cms-htt/Jet2TauFakesFiles.git data

  # - cd ../..
  script:
  - echo "start"
  - echo `ls`
  - ./build plugins/et_analyzer2017.cc test