####################################################
## Script for testing with travis-CI. In order to ##
## do the testing with ROOT, we need to create a  ##
## docker container with ROOT installed. Then, we ##
## can run our tests inside the container.        ##
#################################################### 

# All build envs are for C++
language: cpp

# Use matrix: to explicitly specify the builds
# - Linux: Singular VM with docker, one build for
#          each different image
matrix:
  include:
    - os: linux
      services: docker
      env:
        - DOCKER_IMAGE=rootproject/root-ubuntu16:latest
        - DOCKER_CONTAINER=root-docker
        - SCRIPT_PREFIX_CMD="docker exec $DOCKER_CONTAINER"

# In a C++ project, no clear convention on before_install vs install
# (Travis doesn't do anything automatically). Use it to:
# - Linux: start the base container
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      docker pull $DOCKER_IMAGE
      docker run \
             -itd \
             -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
             --name $DOCKER_CONTAINER $DOCKER_IMAGE
    fi
# Run packaged script to configure, make, run tests
script: $SCRIPT_PREFIX_CMD $TRAVIS_BUILD_DIR/.travis/ciscript.sh